[project]
name = "Embrace AI"
version = "0.1.0"
description = "Virtual Mental Support AI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastrtc[stt]>=0.0.19",
    "kokoro-onnx>=0.4.7",
    "loguru>=0.7.3",
    "ollama>=0.4.7",
	"transformers",
	"torch",
]
